[package]
name = "stateright"
version = "0.1.0"
authors = ["Jonathan Nadal <jon.nadal@gmail.com>"]
license = "MIT"

description = "A library for specifying state machines and model checking invariants."
repository = "https://github.com/stateright/stateright"
readme = "README.md"
categories = ["algorithms", "concurrency", "development-tools", "network-programming", "simulation"]
keywords = ["actor", "distributed-systems", "model-checking", "paxos"]

[dependencies]
crossbeam-utils = "0.6.0"
difference = "2.0.0"
fxhash = "0.2.1"
num_cpus = "1.0"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
clap = "2.30.0"
